[2022-09-24T13:44:25.546+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: encasa.prep manual__2022-09-24T13:44:24.885330+00:00 [queued]>
[2022-09-24T13:44:25.555+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: encasa.prep manual__2022-09-24T13:44:24.885330+00:00 [queued]>
[2022-09-24T13:44:25.556+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2022-09-24T13:44:25.556+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 1
[2022-09-24T13:44:25.557+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2022-09-24T13:44:25.571+0000] {taskinstance.py:1383} INFO - Executing <Task(PythonOperator): prep> on 2022-09-24 13:44:24.885330+00:00
[2022-09-24T13:44:25.593+0000] {standard_task_runner.py:54} INFO - Started process 144 to run task
[2022-09-24T13:44:25.595+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'encasa', 'prep', 'manual__2022-09-24T13:44:24.885330+00:00', '--job-id', '22', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmpr8wmiij7']
[2022-09-24T13:44:25.595+0000] {standard_task_runner.py:83} INFO - Job 22: Subtask prep
[2022-09-24T13:44:25.596+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/***/dags/dag.py
[2022-09-24T13:44:26.078+0000] {task_command.py:384} INFO - Running <TaskInstance: encasa.prep manual__2022-09-24T13:44:24.885330+00:00 [running]> on host bcf5bbb5575a
[2022-09-24T13:44:26.164+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=encasa
AIRFLOW_CTX_TASK_ID=prep
AIRFLOW_CTX_EXECUTION_DATE=2022-09-24T13:44:24.885330+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-09-24T13:44:24.885330+00:00
[2022-09-24T13:44:26.165+0000] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 193, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
TypeError: prep() missing 1 required positional argument: 'date'
[2022-09-24T13:44:26.173+0000] {taskinstance.py:1406} INFO - Marking task as FAILED. dag_id=encasa, task_id=prep, execution_date=20220924T134424, start_date=20220924T134425, end_date=20220924T134426
[2022-09-24T13:44:26.188+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 22 for task prep (prep() missing 1 required positional argument: 'date'; 144)
[2022-09-24T13:44:26.209+0000] {local_task_job.py:164} INFO - Task exited with return code 1
[2022-09-24T13:44:26.242+0000] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
