[2022-09-24T18:12:07.987+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: encasa.colector manual__2022-09-24T13:49:38.592870+00:00 [queued]>
[2022-09-24T18:12:07.997+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: encasa.colector manual__2022-09-24T13:49:38.592870+00:00 [queued]>
[2022-09-24T18:12:07.997+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2022-09-24T18:12:07.997+0000] {taskinstance.py:1363} INFO - Starting attempt 2 of 2
[2022-09-24T18:12:07.998+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2022-09-24T18:12:08.011+0000] {taskinstance.py:1383} INFO - Executing <Task(PythonOperator): colector> on 2022-09-24 13:49:38.592870+00:00
[2022-09-24T18:12:08.015+0000] {standard_task_runner.py:54} INFO - Started process 171 to run task
[2022-09-24T18:12:08.017+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'encasa', 'colector', 'manual__2022-09-24T13:49:38.592870+00:00', '--job-id', '33', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmp2zpvhm_y']
[2022-09-24T18:12:08.018+0000] {standard_task_runner.py:83} INFO - Job 33: Subtask colector
[2022-09-24T18:12:08.019+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/***/dags/dag.py
[2022-09-24T18:12:08.414+0000] {task_command.py:384} INFO - Running <TaskInstance: encasa.colector manual__2022-09-24T13:49:38.592870+00:00 [running]> on host 4f5142878d09
[2022-09-24T18:12:08.472+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=encasa
AIRFLOW_CTX_TASK_ID=colector
AIRFLOW_CTX_EXECUTION_DATE=2022-09-24T13:49:38.592870+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-09-24T13:49:38.592870+00:00
[2022-09-24T18:12:08.474+0000] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 193, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/tasks.py", line 340, in colector
    path = get_path(date=date)
  File "/opt/airflow/dags/tasks.py", line 71, in get_path
    locale.setlocale(locale.LC_ALL, curr)
  File "/usr/local/lib/python3.7/locale.py", line 608, in setlocale
    return _setlocale(category, locale)
locale.Error: unsupported locale setting
[2022-09-24T18:12:08.485+0000] {taskinstance.py:1406} INFO - Marking task as FAILED. dag_id=encasa, task_id=colector, execution_date=20220924T134938, start_date=20220924T181207, end_date=20220924T181208
[2022-09-24T18:12:08.498+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 33 for task colector (unsupported locale setting; 171)
[2022-09-24T18:12:08.511+0000] {local_task_job.py:164} INFO - Task exited with return code 1
[2022-09-24T18:12:08.535+0000] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
