[2022-09-24T17:25:25.436+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: encasa.colector manual__2022-09-24T13:49:38.592870+00:00 [queued]>
[2022-09-24T17:25:25.444+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: encasa.colector manual__2022-09-24T13:49:38.592870+00:00 [queued]>
[2022-09-24T17:25:25.445+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2022-09-24T17:25:25.445+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 1
[2022-09-24T17:25:25.445+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2022-09-24T17:25:25.459+0000] {taskinstance.py:1383} INFO - Executing <Task(PythonOperator): colector> on 2022-09-24 13:49:38.592870+00:00
[2022-09-24T17:25:25.464+0000] {standard_task_runner.py:54} INFO - Started process 315 to run task
[2022-09-24T17:25:25.467+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'encasa', 'colector', 'manual__2022-09-24T13:49:38.592870+00:00', '--job-id', '29', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmpko7p_v0u']
[2022-09-24T17:25:25.468+0000] {standard_task_runner.py:83} INFO - Job 29: Subtask colector
[2022-09-24T17:25:25.469+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/***/dags/dag.py
[2022-09-24T17:25:25.890+0000] {task_command.py:384} INFO - Running <TaskInstance: encasa.colector manual__2022-09-24T13:49:38.592870+00:00 [running]> on host 4f5142878d09
[2022-09-24T17:25:25.966+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=encasa
AIRFLOW_CTX_TASK_ID=colector
AIRFLOW_CTX_EXECUTION_DATE=2022-09-24T13:49:38.592870+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-09-24T13:49:38.592870+00:00
[2022-09-24T17:25:25.968+0000] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 193, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/tasks.py", line 337, in colector
    path = get_path(date=date)
  File "/opt/airflow/dags/tasks.py", line 69, in get_path
    locale.setlocale(locale.LC_ALL, "pt_BR.UTF-8")
  File "/usr/local/lib/python3.7/locale.py", line 608, in setlocale
    return _setlocale(category, locale)
locale.Error: unsupported locale setting
[2022-09-24T17:25:25.978+0000] {taskinstance.py:1406} INFO - Marking task as FAILED. dag_id=encasa, task_id=colector, execution_date=20220924T134938, start_date=20220924T172525, end_date=20220924T172525
[2022-09-24T17:25:25.994+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 29 for task colector (unsupported locale setting; 315)
[2022-09-24T17:25:26.041+0000] {local_task_job.py:164} INFO - Task exited with return code 1
[2022-09-24T17:25:26.082+0000] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
