[2022-09-25T23:45:09.220+0000] {taskinstance.py:1159} INFO - Dependencies not met for <TaskInstance: encasa.colector manual__2022-09-25T23:32:41.540461+00:00 [None]>, dependency 'Trigger Rule' FAILED: Task's trigger rule 'all_success' requires all upstream tasks to have succeeded, but found 1 non-success(es). upstream_tasks_state={'total': 1, 'successes': 0, 'skipped': 0, 'failed': 0, 'upstream_failed': 0, 'done': 0}, upstream_task_ids={'prep'}
[2022-09-25T23:45:09.223+0000] {local_task_job.py:103} INFO - Task is not able to be run
[2022-09-25T23:45:11.548+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: encasa.colector manual__2022-09-25T23:32:41.540461+00:00 [queued]>
[2022-09-25T23:45:11.558+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: encasa.colector manual__2022-09-25T23:32:41.540461+00:00 [queued]>
[2022-09-25T23:45:11.558+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2022-09-25T23:45:11.559+0000] {taskinstance.py:1363} INFO - Starting attempt 3 of 3
[2022-09-25T23:45:11.559+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2022-09-25T23:45:11.576+0000] {taskinstance.py:1383} INFO - Executing <Task(PythonOperator): colector> on 2022-09-25 23:32:41.540461+00:00
[2022-09-25T23:45:11.582+0000] {standard_task_runner.py:54} INFO - Started process 74 to run task
[2022-09-25T23:45:11.584+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'encasa', 'colector', 'manual__2022-09-25T23:32:41.540461+00:00', '--job-id', '77', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmph088w741']
[2022-09-25T23:45:11.585+0000] {standard_task_runner.py:83} INFO - Job 77: Subtask colector
[2022-09-25T23:45:11.586+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/***/dags/dag.py
[2022-09-25T23:45:12.054+0000] {task_command.py:384} INFO - Running <TaskInstance: encasa.colector manual__2022-09-25T23:32:41.540461+00:00 [running]> on host 4f5142878d09
[2022-09-25T23:45:12.118+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=encasa
AIRFLOW_CTX_TASK_ID=colector
AIRFLOW_CTX_EXECUTION_DATE=2022-09-25T23:32:41.540461+00:00
AIRFLOW_CTX_TRY_NUMBER=3
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-09-25T23:32:41.540461+00:00
[2022-09-25T23:45:12.119+0000] {tasks.py:43} INFO - Defining DEC to export information
[2022-09-25T23:45:12.125+0000] {tasks.py:342} INFO - Reading prep dataframe
[2022-09-25T23:45:12.130+0000] {tasks.py:146} INFO - Instantiating the Browser with the requested settings
[2022-09-25T23:45:12.131+0000] {tasks.py:152} INFO - Browser configured
[2022-09-25T23:45:12.132+0000] {logger.py:11} INFO - ====== WebDriver manager ======
[2022-09-25T23:45:12.190+0000] {logger.py:11} INFO - Get LATEST geckodriver version for None firefox
[2022-09-25T23:45:12.191+0000] {logger.py:11} INFO - GH_TOKEN will be used to perform requests
[2022-09-25T23:45:12.592+0000] {logger.py:11} INFO - Driver [/home/***/.wdm/drivers/geckodriver/linux64/0.31/geckodriver] found in cache
[2022-09-25T23:45:13.106+0000] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 193, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/tasks.py", line 344, in colector
    browser = config_browser(config)
  File "/opt/airflow/dags/tasks.py", line 154, in config_browser
    service=FirefoxService(GeckoDriverManager().install()), options=options, firefox_binary=firefox_binary
  File "/home/airflow/.local/lib/python3.7/site-packages/selenium/webdriver/firefox/webdriver.py", line 180, in __init__
    keep_alive=True)
  File "/home/airflow/.local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 270, in __init__
    self.start_session(capabilities, browser_profile)
  File "/home/airflow/.local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 363, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/home/airflow/.local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 428, in execute
    self.error_handler.check_response(response)
  File "/home/airflow/.local/lib/python3.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 243, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.InvalidArgumentException: Message: binary is not a Firefox executable

[2022-09-25T23:45:13.119+0000] {taskinstance.py:1406} INFO - Marking task as FAILED. dag_id=encasa, task_id=colector, execution_date=20220925T233241, start_date=20220925T234511, end_date=20220925T234513
[2022-09-25T23:45:13.133+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 77 for task colector (Message: binary is not a Firefox executable
; 74)
[2022-09-25T23:45:13.162+0000] {local_task_job.py:164} INFO - Task exited with return code 1
[2022-09-25T23:45:13.189+0000] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
