[2022-10-07T20:25:09.747+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: unitintas.colector scheduled__2022-09-01T00:00:00+00:00 [queued]>
[2022-10-07T20:25:09.755+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: unitintas.colector scheduled__2022-09-01T00:00:00+00:00 [queued]>
[2022-10-07T20:25:09.756+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2022-10-07T20:25:09.756+0000] {taskinstance.py:1363} INFO - Starting attempt 2 of 2
[2022-10-07T20:25:09.756+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2022-10-07T20:25:09.768+0000] {taskinstance.py:1383} INFO - Executing <Task(PythonOperator): colector> on 2022-09-01 00:00:00+00:00
[2022-10-07T20:25:09.772+0000] {standard_task_runner.py:54} INFO - Started process 214 to run task
[2022-10-07T20:25:09.774+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'unitintas', 'colector', 'scheduled__2022-09-01T00:00:00+00:00', '--job-id', '442', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmpnpnpcdwh']
[2022-10-07T20:25:09.774+0000] {standard_task_runner.py:83} INFO - Job 442: Subtask colector
[2022-10-07T20:25:09.775+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/***/dags/dag.py
[2022-10-07T20:25:10.180+0000] {task_command.py:384} INFO - Running <TaskInstance: unitintas.colector scheduled__2022-09-01T00:00:00+00:00 [running]> on host 9a36b0424536
[2022-10-07T20:25:10.239+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=unitintas
AIRFLOW_CTX_TASK_ID=colector
AIRFLOW_CTX_EXECUTION_DATE=2022-09-01T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-09-01T00:00:00+00:00
[2022-10-07T20:25:10.240+0000] {tasks.py:39} INFO - Defining DEC to export information
[2022-10-07T20:25:10.245+0000] {tasks.py:360} INFO - Reading prep dataframe
[2022-10-07T20:25:10.258+0000] {tasks.py:153} INFO - Instantiating the Browser with the requested settings
[2022-10-07T20:25:12.828+0000] {tasks.py:167} INFO - Browser configured
[2022-10-07T20:25:12.829+0000] {tasks.py:290} INFO - Removing nan URL values
[2022-10-07T20:25:12.830+0000] {tasks.py:291} INFO - Requested prices before: 0
[2022-10-07T20:25:12.834+0000] {tasks.py:296} INFO - Requested prices after: 0
[2022-10-07T20:25:12.835+0000] {tasks.py:417} INFO - Saved screenshots and prices
[2022-10-07T20:25:12.835+0000] {tasks.py:248} INFO - Test passed
[2022-10-07T20:25:12.836+0000] {tasks.py:274} INFO - Requested prices: 0
[2022-10-07T20:25:12.837+0000] {tasks.py:275} INFO - Scraped prices: 0
[2022-10-07T20:25:12.837+0000] {tasks.py:276} INFO - Day of the scraping: 07/10/2022
[2022-10-07T20:25:12.838+0000] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 193, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/tasks.py", line 419, in colector
    dataframe=dataframe, price=price, url=url, shipping=shipping, date=date, path=path
  File "/opt/airflow/dags/tasks.py", line 279, in append_encomenda
    resultado_coleta, left_on="URL DO INSUMO", right_on="url_coleta", how="left"
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/frame.py", line 9203, in merge
    validate=validate,
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/reshape/merge.py", line 119, in merge
    validate=validate,
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/reshape/merge.py", line 703, in __init__
    self._maybe_coerce_merge_keys()
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/reshape/merge.py", line 1256, in _maybe_coerce_merge_keys
    raise ValueError(msg)
ValueError: You are trying to merge on object and float64 columns. If you wish to proceed you should use pd.concat
[2022-10-07T20:25:12.852+0000] {taskinstance.py:1406} INFO - Marking task as FAILED. dag_id=unitintas, task_id=colector, execution_date=20220901T000000, start_date=20221007T202509, end_date=20221007T202512
[2022-10-07T20:25:12.868+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 442 for task colector (You are trying to merge on object and float64 columns. If you wish to proceed you should use pd.concat; 214)
[2022-10-07T20:25:12.916+0000] {local_task_job.py:164} INFO - Task exited with return code 1
[2022-10-07T20:25:12.949+0000] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
