[2022-09-26T02:55:37.167+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: tudo_melhor.colector scheduled__2022-08-21T00:00:00+00:00 [queued]>
[2022-09-26T02:55:37.177+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: tudo_melhor.colector scheduled__2022-08-21T00:00:00+00:00 [queued]>
[2022-09-26T02:55:37.178+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2022-09-26T02:55:37.178+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 1
[2022-09-26T02:55:37.179+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2022-09-26T02:55:37.192+0000] {taskinstance.py:1383} INFO - Executing <Task(PythonOperator): colector> on 2022-08-21 00:00:00+00:00
[2022-09-26T02:55:37.196+0000] {standard_task_runner.py:54} INFO - Started process 250 to run task
[2022-09-26T02:55:37.199+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'tudo_melhor', 'colector', 'scheduled__2022-08-21T00:00:00+00:00', '--job-id', '43', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmp7ujr57bo']
[2022-09-26T02:55:37.199+0000] {standard_task_runner.py:83} INFO - Job 43: Subtask colector
[2022-09-26T02:55:37.200+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/***/dags/dag.py
[2022-09-26T02:55:37.715+0000] {task_command.py:384} INFO - Running <TaskInstance: tudo_melhor.colector scheduled__2022-08-21T00:00:00+00:00 [running]> on host 8600278d5a66
[2022-09-26T02:55:37.786+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=tudo_melhor
AIRFLOW_CTX_TASK_ID=colector
AIRFLOW_CTX_EXECUTION_DATE=2022-08-21T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-08-21T00:00:00+00:00
[2022-09-26T02:55:37.787+0000] {tasks.py:43} INFO - Defining DEC to export information
[2022-09-26T02:55:37.794+0000] {tasks.py:349} INFO - Reading prep dataframe
[2022-09-26T02:55:37.816+0000] {tasks.py:151} INFO - Instantiating the Browser with the requested settings
[2022-09-26T02:55:37.816+0000] {tasks.py:156} INFO - Browser configured
[2022-09-26T02:55:37.817+0000] {logger.py:11} INFO - ====== WebDriver manager ======
[2022-09-26T02:55:37.906+0000] {logger.py:11} INFO - Get LATEST geckodriver version for 102.3 firefox
[2022-09-26T02:55:37.907+0000] {logger.py:11} INFO - GH_TOKEN will be used to perform requests
[2022-09-26T02:55:38.880+0000] {logger.py:11} INFO - Driver [/home/***/.wdm/drivers/geckodriver/linux64/0.31/geckodriver] found in cache
[2022-09-26T02:55:39.016+0000] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 193, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/tasks.py", line 351, in colector
    browser = config_browser(config)
  File "/opt/airflow/dags/tasks.py", line 159, in config_browser
    options=options,
  File "/home/airflow/.local/lib/python3.7/site-packages/selenium/webdriver/firefox/webdriver.py", line 180, in __init__
    keep_alive=True)
  File "/home/airflow/.local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 270, in __init__
    self.start_session(capabilities, browser_profile)
  File "/home/airflow/.local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 363, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/home/airflow/.local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 428, in execute
    self.error_handler.check_response(response)
  File "/home/airflow/.local/lib/python3.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 243, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: Process unexpectedly closed with status 1

[2022-09-26T02:55:39.033+0000] {taskinstance.py:1406} INFO - Marking task as FAILED. dag_id=tudo_melhor, task_id=colector, execution_date=20220821T000000, start_date=20220926T025537, end_date=20220926T025539
[2022-09-26T02:55:39.060+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 43 for task colector (Message: Process unexpectedly closed with status 1
; 250)
[2022-09-26T02:55:39.096+0000] {local_task_job.py:164} INFO - Task exited with return code 1
[2022-09-26T02:55:39.139+0000] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
