[2022-09-26T02:02:02.654+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: encasa.carga_creation manual__2022-09-26T01:58:51.913110+00:00 [queued]>
[2022-09-26T02:02:02.663+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: encasa.carga_creation manual__2022-09-26T01:58:51.913110+00:00 [queued]>
[2022-09-26T02:02:02.663+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2022-09-26T02:02:02.664+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 1
[2022-09-26T02:02:02.664+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2022-09-26T02:02:02.676+0000] {taskinstance.py:1383} INFO - Executing <Task(PythonOperator): carga_creation> on 2022-09-26 01:58:51.913110+00:00
[2022-09-26T02:02:02.680+0000] {standard_task_runner.py:54} INFO - Started process 472 to run task
[2022-09-26T02:02:02.682+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'encasa', 'carga_creation', 'manual__2022-09-26T01:58:51.913110+00:00', '--job-id', '32', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmp7cxjue8d']
[2022-09-26T02:02:02.683+0000] {standard_task_runner.py:83} INFO - Job 32: Subtask carga_creation
[2022-09-26T02:02:02.684+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/***/dags/dag.py
[2022-09-26T02:02:03.112+0000] {task_command.py:384} INFO - Running <TaskInstance: encasa.carga_creation manual__2022-09-26T01:58:51.913110+00:00 [running]> on host 8600278d5a66
[2022-09-26T02:02:03.175+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=encasa
AIRFLOW_CTX_TASK_ID=carga_creation
AIRFLOW_CTX_EXECUTION_DATE=2022-09-26T01:58:51.913110+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-09-26T01:58:51.913110+00:00
[2022-09-26T02:02:03.175+0000] {tasks.py:526} INFO - Reading results from collect dataframe
[2022-09-26T02:02:03.176+0000] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 193, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/tasks.py", line 527, in carga_creation
    dataframe = pd.read_csv(f"{DEFAULT_PATH}/colector.csv", dtype=str)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 586, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 482, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 811, in __init__
    self._engine = self._make_engine(self.engine)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 1040, in _make_engine
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 51, in __init__
    self._open_handles(src, kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/base_parser.py", line 229, in _open_handles
    errors=kwds.get("encoding_errors", "strict"),
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/common.py", line 707, in get_handle
    newline="",
FileNotFoundError: [Errno 2] No such file or directory: './data_output/colector.csv'
[2022-09-26T02:02:03.186+0000] {taskinstance.py:1406} INFO - Marking task as FAILED. dag_id=encasa, task_id=carga_creation, execution_date=20220926T015851, start_date=20220926T020202, end_date=20220926T020203
[2022-09-26T02:02:03.194+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 32 for task carga_creation ([Errno 2] No such file or directory: './data_output/colector.csv'; 472)
[2022-09-26T02:02:03.216+0000] {local_task_job.py:164} INFO - Task exited with return code 1
[2022-09-26T02:02:03.230+0000] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
