[2022-09-26T01:34:40.092+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: encasa.carga_creation scheduled__2022-09-25T00:00:00+00:00 [queued]>
[2022-09-26T01:34:40.101+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: encasa.carga_creation scheduled__2022-09-25T00:00:00+00:00 [queued]>
[2022-09-26T01:34:40.101+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2022-09-26T01:34:40.101+0000] {taskinstance.py:1363} INFO - Starting attempt 5 of 5
[2022-09-26T01:34:40.102+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2022-09-26T01:34:40.112+0000] {taskinstance.py:1383} INFO - Executing <Task(PythonOperator): carga_creation> on 2022-09-25 00:00:00+00:00
[2022-09-26T01:34:40.117+0000] {standard_task_runner.py:54} INFO - Started process 2298 to run task
[2022-09-26T01:34:40.118+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'encasa', 'carga_creation', 'scheduled__2022-09-25T00:00:00+00:00', '--job-id', '14', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmpbj_4zsi7']
[2022-09-26T01:34:40.119+0000] {standard_task_runner.py:83} INFO - Job 14: Subtask carga_creation
[2022-09-26T01:34:40.119+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/***/dags/dag.py
[2022-09-26T01:34:41.002+0000] {task_command.py:384} INFO - Running <TaskInstance: encasa.carga_creation scheduled__2022-09-25T00:00:00+00:00 [running]> on host 4df58d125c59
[2022-09-26T01:34:41.058+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=encasa
AIRFLOW_CTX_TASK_ID=carga_creation
AIRFLOW_CTX_EXECUTION_DATE=2022-09-25T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=5
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-09-25T00:00:00+00:00
[2022-09-26T01:34:41.059+0000] {tasks.py:521} INFO - Reading results from collect dataframe
[2022-09-26T01:34:41.060+0000] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 193, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/tasks.py", line 522, in carga_creation
    dataframe = pd.read_csv("colector.csv", dtype=str)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 586, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 482, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 811, in __init__
    self._engine = self._make_engine(self.engine)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 1040, in _make_engine
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 51, in __init__
    self._open_handles(src, kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/base_parser.py", line 229, in _open_handles
    errors=kwds.get("encoding_errors", "strict"),
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/common.py", line 707, in get_handle
    newline="",
FileNotFoundError: [Errno 2] No such file or directory: 'colector.csv'
[2022-09-26T01:34:41.069+0000] {taskinstance.py:1406} INFO - Marking task as FAILED. dag_id=encasa, task_id=carga_creation, execution_date=20220925T000000, start_date=20220926T013440, end_date=20220926T013441
[2022-09-26T01:34:41.078+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 14 for task carga_creation ([Errno 2] No such file or directory: 'colector.csv'; 2298)
[2022-09-26T01:34:41.093+0000] {local_task_job.py:164} INFO - Task exited with return code 1
[2022-09-26T01:34:41.108+0000] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
