[2022-09-26T00:19:26.298+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: encasa.carga_creation scheduled__2022-09-25T00:00:00+00:00 [queued]>
[2022-09-26T00:19:26.307+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: encasa.carga_creation scheduled__2022-09-25T00:00:00+00:00 [queued]>
[2022-09-26T00:19:26.308+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2022-09-26T00:19:26.308+0000] {taskinstance.py:1363} INFO - Starting attempt 2 of 2
[2022-09-26T00:19:26.309+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2022-09-26T00:19:26.320+0000] {taskinstance.py:1383} INFO - Executing <Task(PythonOperator): carga_creation> on 2022-09-25 00:00:00+00:00
[2022-09-26T00:19:26.325+0000] {standard_task_runner.py:54} INFO - Started process 677 to run task
[2022-09-26T00:19:26.327+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'encasa', 'carga_creation', 'scheduled__2022-09-25T00:00:00+00:00', '--job-id', '7', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmpga20160c']
[2022-09-26T00:19:26.327+0000] {standard_task_runner.py:83} INFO - Job 7: Subtask carga_creation
[2022-09-26T00:19:26.328+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/***/dags/dag.py
[2022-09-26T00:19:26.810+0000] {task_command.py:384} INFO - Running <TaskInstance: encasa.carga_creation scheduled__2022-09-25T00:00:00+00:00 [running]> on host c726b2151513
[2022-09-26T00:19:26.872+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=encasa
AIRFLOW_CTX_TASK_ID=carga_creation
AIRFLOW_CTX_EXECUTION_DATE=2022-09-25T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-09-25T00:00:00+00:00
[2022-09-26T00:19:26.873+0000] {tasks.py:521} INFO - Reading results from collect dataframe
[2022-09-26T00:19:26.878+0000] {tasks.py:524} INFO - Renaming columns
[2022-09-26T00:19:26.878+0000] {tasks.py:527} INFO - Creating column with print information
[2022-09-26T00:19:26.879+0000] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 193, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/tasks.py", line 534, in carga_creation
    + ".png"
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/ops/common.py", line 69, in new_method
    return method(self, other)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/arraylike.py", line 92, in __add__
    return self._arith_method(other, operator.add)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/series.py", line 5526, in _arith_method
    result = ops.arithmetic_op(lvalues, rvalues, op)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/ops/array_ops.py", line 224, in arithmetic_op
    res_values = _na_arithmetic_op(left, right, op)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/ops/array_ops.py", line 166, in _na_arithmetic_op
    result = func(left, right)
numpy.core._exceptions._UFuncNoLoopError: ufunc 'add' did not contain a loop with signature matching types (dtype('int64'), dtype('<U1')) -> None
[2022-09-26T00:19:26.889+0000] {taskinstance.py:1406} INFO - Marking task as FAILED. dag_id=encasa, task_id=carga_creation, execution_date=20220925T000000, start_date=20220926T001926, end_date=20220926T001926
[2022-09-26T00:19:26.898+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 7 for task carga_creation (ufunc 'add' did not contain a loop with signature matching types (dtype('int64'), dtype('<U1')) -> None; 677)
[2022-09-26T00:19:26.941+0000] {local_task_job.py:164} INFO - Task exited with return code 1
[2022-09-26T00:19:26.956+0000] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
